### ISSUE TITLE
Don't support markdown tables

### ISSUE THREAD

**Issue by electrolyteJ** [streetturtle/jekyll-clean-dark#16]
example 
```
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
```

expect：

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

but:
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

I try to fix issue, but I  has failed. Can you fix the issue.

**Comment by streetturtle** [comment]
Good point! I didn't think about tables. Thanks for raising an issue, I'll have a look.

**Comment by electrolyteJ** [comment]
Nice to your reply，I will still notice this issue。

**Comment by streetturtle** [comment]
Should be ok now: [pavelmakhov.com/jekyll-clean-dark/2018/02/table-styles](http://pavelmakhov.com/jekyll-clean-dark/2018/02/table-styles)

**Comment by electrolyteJ** [comment]
![image](https://user-images.githubusercontent.com/13391139/38025224-2a4f84b2-32ba-11e8-8eb7-db81b66ee1d1.png)

Table is over content boundary, Can you fix the bug ?

**Comment by streetturtle** [comment]
Oops, I'll have a look this weekend. Thanks for letting know!
