### ISSUE TITLE
Favicon problem

### ISSUE THREAD

**Issue by newlifehaonan** [streetturtle/jekyll-clean-dark#17]
Hi,
I am thinking about adding a favicon just as yours "PM", and I add this line 
<link href="{{ '/assets/images/head.ico' | relative_url }}" rel="shortcut icon" type="image/x-icon">
to the header.html file, but it doesn't work, can you tell me how to install the icon? thanks

**Comment by newlifehaonan** [comment]
`<link href="{{ '/assets/images/head.ico' | relative_url }}" rel="shortcut icon" type="image/x-icon">`

**Comment by streetturtle** [comment]
Hi! It seems to work :)
![selection_004](https://user-images.githubusercontent.com/9363150/35489372-0cfee404-0464-11e8-97fd-da7abb3669df.png)

You probably need to clean browser's cache)

**Comment by newlifehaonan** [comment]
oh yeah, it works now after cleaning the cache, thank you!
