### ISSUE TITLE
How to generate TOC?

### ISSUE THREAD

**Issue by alexdhwang** [streetturtle/jekyll-clean-dark#20]
I know there is a `toc.js`, but I don't know how to use it. How to generate a TOC on a page?

**Comment by streetturtle** [comment]
Sorry for that, it was a WIP which didn't work out well. But I've just tried another way of generating toc, based on https://github.com/allejo/jekyll-toc, which worked, please have a look at the latest commit: https://github.com/streetturtle/jekyll-clean-dark/commit/e1d76f0956f0d3dedbb2800caa9b5a013b709d88.

**Comment by streetturtle** [comment]
Did it help?

**Comment by alexdhwang** [comment]
Yes, it helps.
