### ISSUE TITLE
Changing Disqus's content style ?

### ISSUE THREAD

**Issue by zenAndroid** [streetturtle/jekyll-clean-dark#22]
Hello, I am enjoying your theme but i have an issue with it.

It's about the font of the messages in a disqus thread, basically the text is near-invisible as a result of the color of the foreground.

![2018-12-16-050251_440x198_scrot](https://user-images.githubusercontent.com/21260658/50049976-d4d9ce00-00e7-11e9-8c35-a64afd34a287.png)

Do you know how to modify this ? and is it even in my/your control ?

Thank you.

**Comment by streetturtle** [comment]
Hi! I am happy you like it!
Yep, most likely it's a disqus setting - "Color Scheme" under "Appearance", choose "For dark backgrounds". Please let me know it's the case.

**Comment by zenAndroid** [comment]
Nope, it doesn't seem to change anything, the contour of the profile pic becomes white.
![2018-12-19-144758_81x81_scrot](https://user-images.githubusercontent.com/21260658/50244168-38d8ec80-039d-11e9-8930-06097afda53f.png)

But that's it.

Weird :thinking:

**Comment by zenAndroid** [comment]
Anyways, i think sometime soon i'll see if i can change the color of the background to create enough contrast so the text is readable, would be a shame if i abandoned disqus, so i'll do my best to maybe lighten up the colors while keeping the overall theme *DARK* 😀

**Comment by zenAndroid** [comment]
Anyways, thanks @streetturtle for the theme, if you have any other relevant information, please do share, closing this in the meantime.

**Comment by streetturtle** [comment]
I am still pretty sure that the problem is in Disqus's setting - when you set the Color Scheme to "For dark backgrounds" in disqus admin panel then the body element of the disqus iframe has class "dark" which is the case for my blog:

![screenshot from 2018-12-22 17-37-29](https://user-images.githubusercontent.com/9363150/50379175-5bbf0700-0610-11e9-9326-755542dd6767.png)

 but not for yours:

![screenshot from 2018-12-22 17-36-54](https://user-images.githubusercontent.com/9363150/50379177-637eab80-0610-11e9-8d4f-6ac86997edec.png)

**Comment by streetturtle** [comment]
To test you can just manually add class dark to that body element and you'll see.

**Comment by zenAndroid** [comment]
That is exactly what i have, the color scheme is set on 'For dark backgrounds' and yet i have this.

But i think i know where this is coming from, and if my theory is correct, then disqus really needs to get their act together.

See, i am suspecting that the configuation of my blog and another one by the same name are conflicting.
Since on ALSO ON {blog name}:

- First of all, the blog name i have on my posts is Zen Android, which is != zenAndroid

- A few posts from *that* blog are listed.

:weary: I can't say for sure this is the root cause, but it sure seems like it and i dont know why (my admin page on disqus is zenandroid-1.disqus.com) so you'd imagine that since zenandroid-1 != zenandroid there would be no conflicts, but alas, :man_shrugging:

**Comment by zenAndroid** [comment]
![2018-12-22-221236_462x55_scrot](https://user-images.githubusercontent.com/21260658/50380491-bb300d80-0636-11e9-966f-e4ca910da78c.png)
To uniquely identify ...
