### ISSUE TITLE
adding '/' to the end of the url leads to 404

### ISSUE THREAD

**Issue by SunLemuria** [streetturtle/jekyll-clean-dark#23]
Awesome theme! I love it,thanks for sharing.
But there's a little issue.
My chrome adds '/' to the url,so it leads to 404 as you can see:
![404](https://user-images.githubusercontent.com/37478528/50088414-f5b43780-023d-11e9-8e44-9c14a35d6757.png)
![404-3](https://user-images.githubusercontent.com/37478528/50088456-11b7d900-023e-11e9-825a-649ba2223b37.png)
![Image 404-](https://github.com/SunLemuria/images/404-2.png)
seems this haven't been done well

**Comment by streetturtle** [comment]
Good catch! Thanks for informing!

**Comment by SunLemuria** [comment]
perfect!
