### ISSUE TITLE
Font Awesome tag doesn't work

### ISSUE THREAD

**Issue by ThePraeceps** [streetturtle/jekyll-clean-dark#24]
The "tag" icon next to tag's shows up as rectangle suggesting font-awesome isn't configured correctly.

I'm not familiar enough with it to find the source but given it works on your actual blog I'm assuming you'll know what to do.

**Comment by streetturtle** [comment]
Hi! Thank you for using it :+1: 

You need to change the font name here: [theme.scss#L171](https://github.com/ThePraeceps/thepraeceps.github.io/blob/master/assets/css/theme.scss#L171) from _Font Awesome 5 Free_ to _FontAwesome_. And also you can remove this line: [header.html#L20](https://github.com/ThePraeceps/thepraeceps.github.io/blob/master/_includes/header.html#L20)

**Comment by ThePraeceps** [comment]
Hey, thanks for the response :)

I've made those changes and it still doesn't show up properly.

Any further help would be appreciate, web dev really isn't my strong suit.

**Comment by streetturtle** [comment]
I just checked your blog and it seems to be in place:

![screenshot from 2019-02-02 09-37-54](https://user-images.githubusercontent.com/9363150/52165400-5dc7bb80-26ce-11e9-813e-a8b7991f6c1b.png)

Try to open your site in incognito window, maybe it's browser's cache which cached the old css.

**Comment by ThePraeceps** [comment]
That's really weird, even in incognito or ctrl+f5 my browser still shows the square unicode box.
![image](https://user-images.githubusercontent.com/11398530/52185340-9c688d80-2816-11e9-91ff-315e5c97dea7.png)

I also tried it on some other devices, browsers and a VM just to be sure all with the same result.

Is it possible there's the inverse happening where your instance is cacheing over to mine? That would seem like a potential security issue to me.

The CSS when I inspect it looks to be what I would expect.

**Comment by ThePraeceps** [comment]
Found the issue, the name required for me is "Font Awesome 5 Free" and a font-weight of 900 to get the solid version. I also had to link from the css, not the jss

I assume it looks fine to you due to caching of the non-free version.

I also linked the css and not the svg-with-js library.

**Comment by streetturtle** [comment]
Seem the issue is still there. I'll try to fix it this week
