### ISSUE TITLE
Archive returns error 404

### ISSUE THREAD

**Issue by Karabiner980** [streetturtle/jekyll-clean-dark#25]
Hello sir,

I'm setting up my blog and i noticed that when I press the archive button I get a 404 page instead of an archive of my posts.

Your demo version of the theme [here](http://pavelmakhov.com/jekyll-clean-dark/) also produces this error

![image](https://user-images.githubusercontent.com/48854745/55295525-42e3a000-540e-11e9-9887-9cf5cfe90672.png)

I double checked and archive.html is present. The contents of my archive.html are as follows:

```
---
layout: page
title: Blog archive
---
<div class="page-content wc-container">
	<div class="post">
		<h1>Blog Archive</h1>
		{% for post in site.posts %}
			{% capture currentyear %}{{post.date | date: "%Y"}}{% endcapture %}
			{% if currentyear != year %}
				{% unless forloop.first %}</ul>{% endunless %}
					<h5>{{ currentyear }}</h5>
					<ul class="posts">
					{% capture year %}{{currentyear}}{% endcapture %}
				{% endif %}
			<li><a href="{{ post.url | relative_url }}">{{ post.title }}</a></li>
	{% endfor %}
	</div>
</div>
```

**Comment by Karabiner980** [comment]
After some problem solving myself, I figured out a fix. I made a pull request.

**Comment by streetturtle** [comment]
Oops =) I just pushed the fix, almost at the same time as you created a PR.

**Comment by streetturtle** [comment]
Thanks for raising an issue btw!
